[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Connect Netlify Forms to function
[[plugins]]
  package = "@netlify/plugin-functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect all www to non-www
[[redirects]]
  from = "https://www.fridgren.se/*"
  to = "https://fridgren.se/:splat"
  status = 301
  force = true

# Redirect all http to https (www)
[[redirects]]
  from = "http://www.fridgren.se/*"
  to = "https://fridgren.se/:splat"
  status = 301
  force = true

# Redirect all http to https (non-www)
[[redirects]]
  from = "http://fridgren.se/*"
  to = "https://fridgren.se/:splat"
  status = 301
  force = true
